### ISSUE TITLE
Config for bookdown-demo2 (html_book)

### ISSUE THREAD

**Issue by peterdesmet** [rstudio/bookdown-demo#37]
Where can I find the `html_book` settings for the demo at https://bookdown.org/yihui/bookdown-demo2/ which uses the [bootstrap style](https://bookdown.org/yihui/bookdown/html.html#bootstrap-style)?

I want to take a peak, as I can't seem to get my navbar styled properly. 😄

**Comment by peterdesmet** [comment]
Found I should include the `toc.css`, so my issue is resolved. Would still be nice to get a reference to this yaml options from the demo.

```yaml
---
output:
  bookdown::html_book:
    toc: yes
    css: toc.css
---
```
