### ISSUE TITLE
Stroke diagrams overlap vertically

### ISSUE THREAD

**Issue by turnipjs** [rstudio/bookdown-demo#72]
![image](https://github.com/rstudio/bookdown-demo/assets/2893325/0cb0af55-2dd9-42d5-bed3-9190976dbceb)
as seen on [this page](https://practiceplover.com/writing-one-syllable-words.html) as well as others.

**Comment by yihui** [comment]
It'll be nice if you can provide a link to the source project when filing issues, so we can help you more directly.

Anyway, this problem is not relevant to **bookdown**, but a general CSS issue. In `style.css` you have:

```css
.stenobox > p{
    white-space: pre-wrap;
    font-family: Stenodisplay-Dict;
    font-size: 80pt;
    line-height: 1ex;
    padding-top: 4rem;
    padding-bottom: 4rem;
}
```

The `line-height` on line 44 shouldn't use the unit `ex` (`1ex` is too small for your case). Simply define `line-height: 1;` would suffice.
